# Define the runtime configuration
runtime: custom
env: standard
service: amazon-app
# Specify instance settings
instance_class: F2
automatic_scaling:      
  min_num_instances: 1
  max_num_instances: 3

# Resources allocation (adjust as needed)
resources:
  cpu: 2
  memory_gb: 8
  disk_size_gb: 30
  volumes:
    - name: instance
      volume_type: tmpfs
      size_gb: 4
# Allow traffic
handlers:
  - url: /.*
    script: auto
    secure: always

# env_variables:
#   GOOGLE_APPLICATION_CREDENTIALS: "/app/gcs-key.json"  



    